name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check docker installed or not
      run: docker run hello-world
    - name: Push to docker hub
      uses: docker/build-push-action/@v1
      with:
        username: ${{labs.DOCKER_USERNAME}}
        password: ${{labs.DOCKER_PASSWORD}}
        repository: ${{labs.DOCKERHUB_REPO}}
        tag_with_ref: true
